// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnucvgvpremagqficdub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndudWN2Z3ZwcmVtYWdxZmljZHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MjQ3NTMsImV4cCI6MjA3ODIwMDc1M30.OYWYB4gsbpxROFfisUIUfLoVlAxrJCm7bOzRH-g_YP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});